apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubeproapp-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: kubeproapp.cloudgenie.online
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vproapp-service
            port:
              number: 8080