apiVersion: v1
kind: persistentVolumeClaim
metadata:
  name: db-pv-claim
  labels:
    app: vprodb
spec:
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 3i 
  storageClassName: defaults