apiVersion: v1
kind: service
metadata:
  name: vprormq
spec:
  selector:
    app: vpromq01
  ports:
    - name: vprormq-port
      port: 5672
      targetPort: 5672  
      protocol: TCP 
  type: ClusterIP